openapi: "3.0.2"

info:
  title: "Wisata API"
  description: "API untuk pengelolaan data wisata"
  version: "1.0.0"
  contact:
    name: "Developer API Wisata"
    email: "developer@wisataapi.com"

servers:
  - url: "http://localhost:8080"
    description: "Local server"

tags:
  - name: "wisata"
    description: "Operasi terkait wisata"

components:
  schemas:
    Wisata:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        kota:
          type: "string"
        landmark:
          type: "string"
        tarif:
          type: "integer"
          format: "int32"

paths:
  /wisata:
    get:
      summary: "Ambil daftar semua wisata"
      tags:
        - "wisata"
      responses:
        '200':
          description: "Daftar wisata berhasil diambil"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Wisata"
    post:
      summary: "Tambah data wisata"
      tags:
        - "wisata"
      requestBody:
        description: "Data wisata yang akan ditambahkan"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Wisata"
      responses:
        '201':
          description: "Data wisata berhasil ditambahkan"

  /wisata/{id}:
    get:
      summary: "Ambil data wisata berdasarkan ID"
      tags:
        - "wisata"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Data wisata berhasil diambil"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wisata"
    put:
      summary: "Perbarui data wisata berdasarkan ID"
      tags:
        - "wisata"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      requestBody:
        description: "Data wisata yang diperbarui"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Wisata"
      responses:
        '200':
          description: "Data wisata berhasil diperbarui"
    delete:
      summary: "Hapus data wisata berdasarkan ID"
      tags:
        - "wisata"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        '204':
          description: "Data wisata berhasil dihapus"
